// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/zdocs-redesign/Current.tsx": () => import("../components/mockups/zdocs-redesign/Current.tsx"),
  "./components/mockups/zdocs-redesign/Faithful.tsx": () => import("../components/mockups/zdocs-redesign/Faithful.tsx"),
  "./components/mockups/zdocs-redesign/Refined.tsx": () => import("../components/mockups/zdocs-redesign/Refined.tsx")
};
